# this is the test suite for the ENIGMA project

from Enigma_Class import *
from Reflectors import *
from Rotors import *

rotor_1 = RotorV("A", "A")
rotor_2 = RotorII("H", "A")
rotor_3 = RotorIV("G", "A")
reflector = ReflectorB()

"""
# just test that the rotor rotates correctly
rotor_1_bis = RotorI("Z", "A")
text = ""
for i in range(7):
    rotor_1_bis.rotate()
    text += rotor_1_bis.cypher("A")

assert text == "EJKCHBX"

rotor_2_bis = RotorII("Z", "A")
text = ""
for i in range(7):
    rotor_2_bis.rotate()
    text += rotor_2_bis.cypher("A")

assert text == "AIBHODL"
"""

enigma = Enigma(rotor_1, rotor_2, rotor_3, reflector, "")

text_cyphered = enigma.cypher("WNLEQ IEWHV JHANH OPOLW EENWJ ADREZ CXJMV LQUUT EEILV JZQUJ ESIRT GWTRM JIPMP BRHIP NVXLQ USMPH GKWGD GGSBN TVQHQ XBGIW RJKKQ XMVUU VTFRI AWQSR SJAUK PFAYQ MKDXF KKZYX JQOVL HIEMA GNHWC PVGLK VSPAA WPGKJ XZHVP CUJJJ RYQCX CQSRM RRKMA NVGUK SZADZ ZSYXM HEYYI KNHHS CHOUR OUJAJ UQXYD OGMEI RORJO KNIFU VTPDH XIJGJ FSOES FJBOM QHJIN BQVCV JHVFV MGHRG ZJMDW EGHTQ NADEI SANSX UQRTR WPROA WHFDA REEXX KHFOO MPHDN ZPDPG COZZV NLSKP MJKXO FWNGJ MJVZO IQAAE XPSHD UKHAE NKZTW HKBVJ WYCJN YXVZN STMZM OOVUR TGTGQ SNZWI RFWVW YCAGV UKBCB UNOCW IXTYF ONLTC RUUXV VBDFY VGYTK CGCBC SUIOK JCMBW NUNXZ MQWJB CRLLU UUYJP XDCQT PJZQL LCVKD DSUIS MNSJI EURKK ISERM GQELW GDNJF JOQUY ATGLK QFWEM AOYXV JDIGT CRHQX KNOIN UYFEN IODSV LXUKP LBWUB NLWSZ CKPIQ YEKLY NZWNF TDEVR JYJXF YLTLY XVRCS FNKCT KHINH EZVGZ YJDVS QSTVE EZVKI IJJFE COACM PESCY AYLML QCKZV HEDAN MHOHE FPNHV ZYBZI JBORU TSKKO ZTSSE DMHGY TOAXP UBAVD QFBYY SZYMX YWZMX ZIBON RYKPR ZIWRP PDMUB ADTCA EPJIG QRZAO NRWSD ORKPV GCVKG EONWF FJBHG SKSPH CUNJH VTNWI NWLSZ CRPHF ALNIF LNJNK SHXQM UQEJG EKPOT MMSVZ RASQQ XAMON TZAEW QJQGC SRZWN NEIBX TAMHA OMBKD GYFUJ GIKWH QIUMF TOCYV SLQEV VKVMQ EVYXN VVUMF JLRXP RVGPU CVDSS TZLNC QEDGF LJEUV LOEVY UJTLA OQCXX RRUGN FBZFK UDDPR UXSKC MFLTJ SBYTG DJPUW NFDXL YSPOQ FLQMS XWFLH YPIRY XICAS KZLAT SXYMY NJPPZ JTHPR OYSDO IUBDF OFPHP MQTFD TUMLT VCSYR KWG")
print(text_cyphered)
# assert text_cyphered == "VOILA UN TEXTE BIEN INITERESSANT MAIS QUI VAUT QUAND MEME LA PEINE D ETRE ENCRYPTE DE MANIERE CORRECTE A MON AVIS"
